let mex = `<select class="mexico" name="pais" class="options required pregunta" data-preg="2" id="mexico"  data-id-pregunta="45">
                                    <option hidden="" value="">Seleciona un opción (Select an option)</option>
                                    <option value="Aguascalientes">Aguascalientes</option>
                                    <option value="B. C.">Baja California</option>
                                    <option value="B. C. Sur">Baja California Sur</option>
                                    <option value="Campeche">Campeche</option>
                                    <option value="CDMX">CDMX</option>
                                    <option value="Chiapas">Chiapas</option>
                                    <option value="Chihuahua">Chihuahua</option>
                                    <option value="Coahuila">Coahuila de Zaragoza</option>
                                    <option value="Colima">Colima</option>
                                    <option value="Durango">Durango</option>
                                    <option value="Guanajuato">Guanajuato</option>
                                    <option value="Guerrero">Guerrero</option>
                                    <option value="Hidalgo">Estado de Hidalgo</option>
                                    <option value="Jalisco">Jalisco</option>
                                    <option value="Edo-de-Mexico">Estado de México</option>
                                    <option value="Michoacan">Michoacán de Ocampo</option>
                                    <option value="Morelos">Morelos</option>
                                    <option value="Nayarit">Nayarit</option>
                                    <option value="Nvo-Leon">Nuevo León</option>
                                    <option value="Oaxaca">Oaxaca</option>
                                    <option value="Puebla">Puebla</option>
                                    <option value="Queretaro">Querétaro</option>
                                    <option value="Quintana-Roo">Quintana Roo</option>
                                    <option value="SLP">San Luis Potosí</option>
                                    <option value="Sinaloa">Sinaloa</option>
                                    <option value="Sonora">Sonora</option>
                                    <option value="Tabasco">Tabasco</option>
                                    <option value="Tamaulipas">Tamaulipas</option>
                                    <option value="Tlaxcala">Tlaxcala</option>
                                    <option value="Veracruz">Veracruz</option>
                                    <option value="Yukatan">Yucatán</option>
                                    <option value="Zacatecas">Zacatecas</option>
                                </select>`;

let eua = `<select name="" class="options united"  data-id-pregunta="43">
<option hidden="" value="">Seleciona un opción (Select an option)</option>
<option value="Alabama">Alabama (Alebama)</option>
<option value="Alaska">Alaska (Alaska)</option>
<option value="Arizona">Arizona (Arizona)</option>
<option value="Arkansas">Arkansas (Arkansas)</option>
<option value="California">California (California)</option>
<option value="Carolina-del-Norte">Carolina del Norte (North Carolina)</option>
<option value="Carolina-del-Sur">Carolina del Sur (South Carolina)</option>
<option value="Colorado">Colorado (Colorado)</option>
<option value="Connecticut">Connecticut (Connecticut)</option>
<option value="Dakota-del-Norte">Dakota del Norte (North Dakota)</option>
<option value="Dakota-del-Sur">Dakota del Sur (South Dakota)</option>
<option value="Delaware">Delaware (Delaware)</option>
<option value="Illinois">Illinois (Illinois)</option>
<option value="Indiana">Indiana (IN)</option>
<option value="lowa">lowa (lowa)</option>
<option value="Kansas">Kansas (Kansas)</option>
<option value="Kentucky">Kentucky (kenucky)</option>
<option value="Luisiana">Luisiana (Luisiana)</option>
<option value="Maine">Maine (Maine)</option>
<option value="Maryland">Maryland (Maryland)</option>
<option value="Massachusetts ">Massachusetts  (Massachusetts )</option>
<option value="Michigan">Michigan (Michigan)</option>
<option value="Minnesota">Minnesota (Minesota)</option>
<option value="Misispi">Misispi (Mississippi)</option>
<option value="Misuri">Misuri (MISSOURI)</option>
<option value="Montana">Montana (Montana)</option>
<option value="Nebraska">Nebraska (Nebraska)</option>
<option value="Nevada">Nevada (Nevada)</option>
<option value="Nva-Jersey">Nueva Jersey (New jersey)</option>
<option value="Nva-York">Nueva York (New York)</option>
<option value="Nvo-Hampshire ">Nuevo Hampshire (New Hampshire)</option>
<option value="Nvo-Mexico">Nuevo Mexico (New Mexico)</option>
<option value="Ohio">Ohio (Ohio)</option>
<option value="Oklahoma">Oklahoma (Oklahoma)</option>
<option value="Oregon">Oregón (Oregon)</option>
<option value="Pensilvania">Pensilvania (Pennsylvania)</option>
<option value="Rhode-Island">Rhode Island (Rhode Island)</option>
<option value="Tennessee">Tennessee (Tennessee)</option>
<option value="Texas">Texas (Texas)</option>
<option value="Utah">Utah (Utah)</option>
<option value="Vermont">Vermont (Vermont)</option>
<option value="Virginia">Virginia (Virginia)</option>
<option value="Virginia-Occidental">Virginia Occidental (West Virginia)</option>
<option value="Washington">Washington (Washington)</option>
<option value="Wisconsin">Wisconsin (Wisconsin)</option>
<option value="Wyoming">Wyoming (Wyoming)</option>
</select>`;

let chih = `<select name="" style="width: 100%;" class="options mex"  data-id-pregunta="44">
<option hidden="" value="">Seleciona un opción (Select an option)</option>
<option value="Ahumada">Ahumada</option>
<option value="Aldama">Aldama</option>
<option value="Allende">Allende</option>
<option value="Aquiles-Serdán">Aquiles Serdán</option>
<option value="Bachíniva">Bachíniva</option>
<option value="Balleza">Balleza</option>
<option value="Batopilas">Batopilas</option>
<option value="Bocoyna">Bocoyna</option>
<option value="Buenaventura">Buenaventura</option>
<option value="Camargo">Camargo</option>
<option value="Carichí">Carichí</option>
<option value="Casas-Grandes">Casas Grandes</option>
<option value="Cuauhtémoc">Cuauhtémoc</option>
<option value="Chihuahua">Chihuahua</option>
<option value="Chínipas">Chínipas</option>
<option value="Coronado">Coronado</option>
<option value="Cusihuiriachi">Cusihuiriachi</option>
<option value="Coyame">Coyame</option>
<option value="Delicias">Delicias</option>
<option value="Dr-Belisario-Domínguez">Dr. Belisario Domínguez</option>
<option value="Galeana">Galeana</option>
<option value="Santa-Isabel">Santa Isabel</option>
<option value="Gómez-Farías">Gómez Farías</option>
<option value="Gran-Morelos">Gran Morelos</option>
<option value="Guachochi">Guachochi</option>
<option value="Guadalupe">Guadalupe</option>
<option value="Guadalupe-y-Calvo">Guadalupe y Calvo</option>
<option value="Guazapares">Guazapares</option>
<option value="Guerrero">Guerrero</option>
<option value="Hidalgo-del-Parral">Hidalgo del Parral</option>
<option value="Huejotitán">Huejotitán</option>
<option value="Ignacio-Zaragoza">Ignacio Zaragoza</option>
<option value="Janos">Janos</option>
<option value="Jiménez">Jiménez</option>
<option value="Juárez">Juárez</option>
<option value="Julimes">Julimes</option>
<option value="López">López</option>
<option value="Madera">Madera</option>
<option value="Maguarichi">Maguarichi</option>
<option value="Manuel-Benavides">Manuel Benavides</option>
<option value="Matachí">Matachí</option>
<option value="Matamoros">Matamoros</option>
<option value="Meoqui">Meoqui</option>
<option value="Morelos">Morelos</option>
<option value="Moris">Moris</option>
<option value="Namiquipa">Namiquipa</option>
<option value="Nonoava">Nonoava</option>
<option value="Nuevo-Casas-Grandes">Nuevo Casas Grandes</option>
<option value="Ocampo">Ocampo</option>
<option value="Ojinaga">Ojinaga</option>
<option value="Praxedis-G-Guerrero">Praxedis G. Guerrero</option>
<option value="Riva-Palacio">Riva Palacio</option>
<option value="Rosales">Rosales</option>
<option value="Rosario">Rosario</option>
<option value="San-Fco-de-Borja">San Francisco de Borja</option>
<option value="San-Fco-de-Conchos">San Francisco de Conchos</option>
<option value="San-Fco-del-Oro">San Francisco del Oro</option>
<option value="Santa-Bárbara">Santa Bárbara</option>
<option value="Satevó">Satevó</option>
<option value="Saucillo">Saucillo</option>
<option value="Temósachic">Temósachic</option>
<option value="El-Tule">El-Tule</option>
<option value="Urique">Urique</option>
<option value="Uruachi">Uruachi</option>
<option value="Valle-de-Zaragoza">Valle de Zaragoza</option>
</select>`

let inter = `<select id="inter" name="pais" class="options required"  data-id-pregunta="26">
<option hidden="" value="">Seleciona un opción (Select an option)</option>
<option value="Estados-Unidos">Estados Unidos (United States)</option>
<option value="Alemania">Alemania (Germany)</option>
<option value="Brasil">Brasil (Brazil)</option>
<option value="Canadá">Canadá (Canada)</option>
<option value="China">China (China)</option>
<option value="Colombia">Colombia (Colombia)</option>
<option value="Francia">Francia (France)</option>
<option value="Italia">Italia (Italy)</option>
<option value="Panamá">Panamá (Panama)</option>
<option value="Perú">Perú (Peru)</option>
<option value="Puerto-Rico">Puerto Rico (Puerto Rico)</option>
<option value="Rusia">Rusia (Russia)</option>
<option value="Suiza">Suiza (Switzerland)</option>
<option value="Afganistán">Afganistán (Afghanistan)</option>
<option value="Albania">Albania (Albania)</option>
<option value="Andorra">Andorra (Andorra)</option>
<option value="Angola">Angola (Angola)</option>
<option value="Anguilla">Anguilla (Anguilla)</option>
<option value="Antártida">Antártida (Antarctica)</option>
<option value="Antigua-y-Barbuda">Antigua y Barbuda (Antigua and Barbuda)</option>
<option value="Antillas-Holandesas">Antillas Holandesas (Netherlands Antilles)</option>
<option value="Arabia-Saudita">Arabia Saudita (Saudi Arabia)</option>
<option value="Argelia">Argelia (Algeria)</option>
<option value="Argentina">Argentina (Argentina)</option>
<option value="Armenia">Armenia (Armenia)</option>
<option value="Aruba">Aruba (Aruba)</option>
<option value="Australia">Australia (Australia)</option>
<option value="Austria">Austria (Austria)</option>
<option value="Azerbaiyán">Azerbaiyán (Azerbaijan)</option>
<option value="Bahamas">Bahamas (Bahamas)</option>
<option value="Bangladesh">Bangladesh (Bangladesh)</option>
<option value="Barbados">Barbados (Barbados)</option>
<option value="Baréin">Baréin (Bahrain)</option>
<option value="Bélgica">Bélgica (Belgium)</option>
<option value="Belice">Belice (Belize)</option>
<option value="Benín">Benín (Benin)</option>
<option value="Bermudas">Bermudas (Bermuda)</option>
<option value="Bielorrusia">Bielorrusia (Belarus)</option>
<option value="Bolivia">Bolivia (Bolivia)</option>
<option value="Bosnia-y-Herzegovina">Bosnia-Herzegovina (Bosnia and Herzegovina)</option>
<option value="Botsuana">Botsuana (Botswana)</option>
<option value="Brunei-Darussalam">Brunei Darussalam (Brunei Darussalam)</option>
<option value="Bulgaria">Bulgaria (Bulgaria)</option>
<option value="Burkina-Faso">Burkina Faso (Burkina Faso)</option>
<option value="Burundi">Burundi (Burundi)</option>
<option value="Bután">Bután (Bhutan)</option>
<option value="Cabo-Verde">Cabo Verde (Cape Verde)</option>
<option value="Camboya">Camboya (Cambodia)</option>
<option value="Camerún">Camerún (Cameroon)</option>
<option value="Chad">Chad (Chad)</option>
<option value="Chile">Chile (Chile)</option>
<option value="Chipre">Chipre (Cyprus)</option>
<option value="Ciudad-del-Vaticano">Ciudad del Vaticano (Vatican City)</option>
<option value="Comores">Comores (Comoros)</option>
<option value="Corea-del-Norte">Corea del Norte (North Korea)</option>
<option value="Corea-del-Sur">Corea del Sur (South Korea)</option>
<option value="Costa-de-Marfil">Costa de Marfil (Ivory Coast (Cote d'Ivoire))</option>
<option value="Costa-Rica">Costa Rica (Costa Rica)</option>
<option value="Croacia">Croacia (Croatia)</option>
<option value="Cuba">Cuba (Cuba)</option>
<option value="Dinamarca">Dinamarca (Denmark)</option>
<option value="Djibouti">Djibouti, Yibuti (Djibouti)</option>
<option value="Dominica">Dominica (Dominica)</option>
<option value="Ecuador">Ecuador (Ecuador)</option>
<option value="Egipto">Egipto (Egypt)</option>
<option value="El-Salvador">El Salvador (El Salvador)</option>
<option value="Emiratos">Emiratos Árabes Unidos (United Arab Emirates)</option>
<option value="Eritrea">Eritrea (Eritrea)</option>
<option value="Eslovaquia">Eslovaquia (Slovakia (Slovak Republic))</option>
<option value="Eslovenia">Eslovenia (Slovenia)</option>
<option value="España">España (Spain)</option>
<option value="Estonia">Estonia (Estonia)</option>
<option value="Etiopía">Etiopía (Ethiopia)</option>
<option value="Filipinas">Filipinas (Philippines)</option>
<option value="Finlandia">Finlandia (Finland)</option>
<option value="Fiyi">Fiyi (Fiji)</option>
<option value="Gabón">Gabón (Gabon)</option>
<option value="Gambia">Gambia (The Gambia)</option>
<option value="Georgia">Georgia (Georgia)</option>
<option value="Ghana">Ghana (Ghana)</option>
<option value="Gibraltar">Gibraltar (Gibraltar)</option>
<option value="Granada">Granada (Grenada)</option>
<option value="Grecia">Grecia (Greece)</option>
<option value="Groenlandia">Groenlandia (Greenland)</option>
<option value="Guadalupe">Guadalupe (Guadeloupe)</option>
<option value="Guam">Guam (Guam)</option>
<option value="Guatemala">Guatemala (Guatemala)</option>
<option value="Guayana-Francesa">Guayana Francesa (French Guiana)</option>
<option value="Guinea">Guinea (Guinea)</option>
<option value="Guinea-Ecuatorial">Guinea Ecuatorial (Equatorial Guinea)</option>
<option value="Guinea-Bisáu">Guinea-Bisáu (Guinea-Bissau)</option>
<option value="Guyana">Guyana (Guyana)</option>
<option value="Haití">Haití (Haiti)</option>
<option value="Honduras">Honduras (Honduras)</option>
<option value="Hong-Kong">Hong Kong (Hong Kong)</option>
<option value="Hungría">Hungría (Hungary)</option>
<option value="India">India (India)</option>
<option value="Indonesia">Indonesia (Indonesia)</option>
<option value="Irán">Irán (Iran (Islamic Republic of))</option>
<option value="Iraq">Iraq (Iraq)</option>
<option value="Irlanda">Irlanda (Ireland)</option>
<option value="Isla-de-Navidad">Isla de Navidad, Isla Christmas (Christmas Island)</option>
<option value="Isla-Pitcairn">Isla Pitcairn (Pitcairn Island)</option>
<option value="Islandia">Islandia (Iceland)</option>
<option value="Irán">Irán (Iran)</option>
<option value="Irlanda">Irlanda (Ireland)</option>
<option value="Islandia">Islandia (Iceland)</option>
<option value="Islas-Caimán">Islas Caimán (Cayman Islands)</option>
<option value="Islas-Cocos">Islas Cocos (Cocos (Keeling) Islands)</option>
<option value="Islas-Cook">Islas Cook (Cook Islands)</option>
<option value="Islas-Feroe">Islas Feroe (Faroe Islands)</option>
<option value="Islas-Malvinas">Islas Malvinas (Falkland Islands)</option>
<option value="Islas-Marianas-del-Norte">Islas Marianas del Norte (Northern Mariana Islands)</option>
<option value="Islas-Marshall">Islas Marshall (Marshall Islands)</option>
<option value="Islas-Salomón">Islas Salomón (Solomon Islands)</option>
<option value="Islas-Turcas-y-Caicos">Islas Turcas y Caicos (Turks and Caicos Islands)</option>
<option value="Islas-Virgenes-Británicas">Islas Virgenes Británicas (Virgin Islands (British))</option>
<option value="Islas-Vírgenes-de-los-Estados-Unidos">Islas Vírgenes de los Estados Unidos (Virgin Islands (U.S.A.))</option>
<option value="Israel">Israel (Israel)</option>
<option value="Jamaica">Jamaica (Jamaica)</option>
<option value="Japón">Japón (Japan)</option>
<option value="Jordania">Jordania (Jordan)</option>
<option value="Kazajistán">Kazajistán (Kazakhstan)</option>
<option value="Kenia">Kenia (Kenya)</option>
<option value="Kirguistán">Kirguistán (Kyrgyzstan)</option>
<option value="Kiribati">Kiribati (Kiribati)</option>
<option value="Kosovo">Kosovo (Kosovo)</option>
<option value="Kuwait">Kuwait (Kuwait)</option>
<option value="Laos">Laos (República Democrática Popular) (Laos, People's Democratic Republic)</option>
<option value="Lesoto">Lesoto (Lesotho)</option>
<option value="Letonia">Letonia (Latvia)</option>
<option value="Líbano">Líbano (Lebanon)</option>
<option value="Liberia">Liberia (Liberia)</option>
<option value="Libia">Libia (Libya)</option>
<option value="Liechtenstein">Liechtenstein (Liechtenstein)</option>
<option value="Lituania">Lituania</option>
<option value="Luxemburgo">Luxemburgo (Luxembourg)</option>
<option value="Macao">Macao (Macau)</option>
<option value="Macedonia-del-Norte">Macedonia del Norte (North Macedonia)</option>
<option value="Madagascar">Madagascar (Madagascar)</option>
<option value="Malasia">Malasia (Malaysia)</option>
<option value="Malawi">Malawi (Malawi)</option>
<option value="Maldivas">Maldivas (Maldives)</option>
<option value="Mali">Malí (Mali)</option>
<option value="Malta">Malta (Malta)</option>
<option value="Marruecos">Marruecos (Morocco)</option>
<option value="Martinica">Martinica (Martinique)</option>
<option value="Mauricio">Mauricio (Mauritius)</option>
<option value="Mauritania">Mauritania (Mauritania)</option>
<option value="Mayotte">Mayotte (Mayotte)</option>
<option value="Micronesia">Micronesia (Micronesia)</option>
<option value="Moldavia">Moldavia (Moldova)</option>
<option value="Mónaco">Mónaco (Monaco)</option>
<option value="Mongolia">Mongolia (Mongolia)</option>
<option value="Montenegro">Montenegro (Montenegro)</option>
<option value="Montserrat">Montserrat (Montserrat)</option>
<option value="Mozambique">Mozambique (Mozambique)</option>
<option value="Namibia">Namibia (Namibia)</option>
<option value="Nauru">Nauru (Nauru)</option>
<option value="Nepal">Nepal (Nepal)</option>
<option value="Nicaragua">Nicaragua (Nicaragua)</option>
<option value="Níger">Níger (Niger)</option>
<option value="Nigeria">Nigeria (Nigeria)</option>
<option value="Niue">Niue (Niue)</option>
<option value="Noruega">Noruega (Norway)</option>
<option value="Nueva-Caledonia">Nueva Caledonia (New Caledonia)</option>
<option value="Nueva-Zelanda">Nueva Zelanda (New Zealand)</option>
<option value="Omán">Omán (Oman)</option>
<option value="Países-Bajos">Países Bajos (Netherlands)</option>
<option value="Pakistán">Pakistán (Pakistan)</option>
<option value="Palau">Palau (Palau)</option>
<option value="Palestina">Palestina (Palestine)</option>
<option value="Papúa-Nueva-Guinea">Papúa Nueva Guinea (Papua New Guinea)</option>
<option value="Paraguay">Paraguay (Paraguay)</option>
<option value="Polinesia-Francesa">Polinesia Francesa (French Polynesia)</option>
<option value="Polonia">Polonia (Poland)</option>
<option value="Portugal">Portugal (Portugal)</option>
<option value="Qatar">Qatar (Qatar)</option>
<option value="Reino-Unido">Reino Unido (United Kingdom)</option>
<option value="Rep.-Centroafricana">República Centroafricana (Central African Republic)</option>
<option value="Rep.-Checa">República Checa (Czech Republic)</option>
<option value="Rep.-del-Congo">República del Congo (Congo, Republic of (Brazzaville))</option>
<option value="Rep.-Democrática-del-Congo">República Democrática del Congo (Democratic Republic of the Congo)</option>
<option value="Congo">Congo (Kinshasa)</option>
<option value="Rep.-Dominicana">República Dominicana (Dominican Republic)</option>
<option value="Reunión">Reunión (Réunion)</option>
<option value="Ruanda">Ruanda (Rwanda)</option>
<option value="Rumanía">Rumanía (Romania)</option>
<option value="Sáhara-Occidental">Sáhara Occidental (Western Sahara)</option>
<option value="Samoa">Samoa (Samoa)</option>
<option value="Samoa-Americana">Samoa Americana (American Samoa)</option>
<option value="San-Cristóbal-y-Nieves">San Cristóbal y Nieves (Saint Kitts and Nevis)</option>
<option value="San-Marino">San Marino (San Marino)</option>
<option value="San-Vicente-y-las-Granadinas">San Vicente y las Granadinas (Saint Vincent and the Grenadines)</option>
<option value="Sta.-Lucía">Santa Lucía (Saint Lucia)</option>
<option value="Sto-Tomé-y-Príncipe">Santo Tomé y Príncipe (Sao Tome and Principe)</option>
<option value="Senegal">Senegal (Senegal)</option>
<option value="Serbia">Serbia (Serbia)</option>
<option value="Seychelles">Seychelles (Seychelles)</option>
<option value="Sierra-Leona">Sierra Leona (Sierra Leone)</option>
<option value="Singapur">Singapur (Singapore)</option>
<option value="Siria">Siria (Syria, Syrian Arab Republic)</option>
<option value="Somalia">Somalia (Somalia)</option>
<option value="Sri-Lanka">Sri Lanka (Sri Lanka)</option>
<option value="Suzilandia">Suzilandia, Esuatini (Swaziland (Eswatini))</option>
<option value="Sudáfrica">Sudáfrica (South Africa)</option>
<option value="Sudán">Sudán (Sudan)</option>
<option value="Sudán-del-Sur">Sudán del Sur (South Sudan)</option>
<option value="Suecia">Suecia (Sweden)</option>
<option value="Surinam">Surinam (Suriname)</option>
<option value="Tailandia">Tailandia (Thailand)</option>
<option value="Taiwán">Taiwán (República de China) (Taiwan (Republic of China))</option>
<option value="Tanzania">Tanzania (Tanzania)</option>
<option value="Tayikistán">Tayikistán (Tajikistan)</option>
<option value="Tíbet">Tíbet (Tibet)</option>
<option value="Timor-Oriental">Timor Oriental (East Timor)</option>
<option value="Togo">Togo (Togo)</option>
<option value="Tokelau">Tokelau (Tokelau)</option>
<option value="Tonga">Tonga (Tonga)</option>
<option value="Trinidad-y-Tobago">Trinidad y Tobago (Trinidad and Tobago)</option>
<option value="Túnez">Túnez (Tunisia)</option>
<option value="Turkmenistán">Turkmenistán (Turkmenistan)</option>
<option value="Turquía">Turquía (Turkey)</option>
<option value="Turkmenistán">Turkmenistán (Turkmenistan)</option>
<option value="Turquía">Turquía (Türkiye (Turkey))</option>
<option value="Tuvalu">Tuvalu (Tuvalu)</option>
<option value="Ucrania">Ucrania (Ukraine)</option>
<option value="Uganda">Uganda (Uganda)</option>
<option value="Uruguay">Uruguay (Uruguay)</option>
<option value="Uzbekistán">Uzbekistán (Uzbekistan)</option>
<option value="Vanuatu">Vanuatu (Vanuatu)</option>
<option value="Venezuela">Venezuela (Venezuela)</option>
<option value="Vietnam">Vietnam (Vietnam)</option>
<option value="Wallis-y-Futuna">Wallis y Futuna (Wallis and Futuna Islands)</option>
<option value="Yemen">Yemen (Yemen)</option>
<option value="Zambia">Zambia (Zambia)</option>
<option value="Zimbabwe">Zimbabwe (Zimbabwe)</option>
</select>`;